---
extends: eslint-config-shakacode
plugins:
- react-native
- flowtype
env:
  mocha: true
  browser: true
  node: true
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".android.js"
      - ".ios.js"
      moduleDirectory:
      - ".."
      - node_modules
  flowtype:
    onlyFilesWithFlowAnnotation: true
globals:
  __DEV__: true
  ReactClass: true
  ReactElement: true
rules:
  react-native/no-unused-styles: 2
  react-native/split-platform-components: 2
  react-native/no-inline-styles: 2
  react-native/no-color-literals: 2
  react/jsx-no-bind: 1
  react/prefer-stateless-function: 1
  react/jsx-indent: 1
  flowtype/require-parameter-type: 1
  flowtype/require-return-type:
  - 0
  - always
  - annotateUndefined: never
  flowtype/space-after-type-colon:
  - 1
  - always
  flowtype/space-before-type-colon:
  - 1
  - never
  flowtype/type-id-match:
  - 1
  - "^([A-Z][a-z0-9]+)+Type$"

  react/jsx-filename-extension:
    - 1
    - extensions: [".js", ".jsx"]
